// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDpMJLZOpFD2INgSer4Zi_2T-9CCuT_ZEk',
    appId: '1:338860676502:web:ccd68f04a26f9389b8f9b7',
    messagingSenderId: '338860676502',
    projectId: 'rozgaar-7fdda',
    authDomain: 'rozgaar-7fdda.firebaseapp.com',
    storageBucket: 'rozgaar-7fdda.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBswIdZTIQATlyQJMqrDopB40oWoo8XBlw',
    appId: '1:338860676502:android:757c72b67bf56239b8f9b7',
    messagingSenderId: '338860676502',
    projectId: 'rozgaar-7fdda',
    storageBucket: 'rozgaar-7fdda.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDSeI130pzLFzR7u81rJG2pnoU0F_utpOI',
    appId: '1:338860676502:ios:e151103d01f5b6f8b8f9b7',
    messagingSenderId: '338860676502',
    projectId: 'rozgaar-7fdda',
    storageBucket: 'rozgaar-7fdda.appspot.com',
    iosBundleId: 'com.example.code',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDSeI130pzLFzR7u81rJG2pnoU0F_utpOI',
    appId: '1:338860676502:ios:61633dc91f508c8db8f9b7',
    messagingSenderId: '338860676502',
    projectId: 'rozgaar-7fdda',
    storageBucket: 'rozgaar-7fdda.appspot.com',
    iosBundleId: 'com.example.code.RunnerTests',
  );
}
